### ISSUE TITLE
Arrow indicator

### ISSUE THREAD

**Issue by thisconnect** [Fyrd/purejs-datalist-polyfill#2]
Hi, this is a nice polyfill. Do you still use it yourself?

Would it be possible to implement the arrow on focus to indicate that there are options?

**Comment by tdolphin** [comment]
To show the options on focus, in the function buildlist, I changed the line isFound to
```javascript
var isFound = (query.length<1) || (query.length && item.innerText.toLowerCase().indexOf( query ) > -1);
```
For the arrow, I added a span with class darrow after the input
```html
<input type="text" list="states"><span class="darrow"></span>
```
```css
.darrow:after{
	content: '';
	display: inline-block;
	position: relative;
	top: 3px;
	left: -16px;
	width: 0;
	height: 0;
	border-top: 5px solid black;
	border-right: 5px solid transparent;
	border-bottom: 5px solid transparent;
	border-left: 5px solid transparent;
}
```
